# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
FEATURES="binpkg-request-signature clean-logs collision-protect getbinpkg strict"
MAKEOPTS="--jobs 6"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled
USE="-Xaw3d -a52 -aqua -bluetooth -clamav -css -cups -dvd -emacs -gnome -gnome-keyring -ibm -ieee1394 -ipod -kde -ldap -motif -nas -plasma -secureboot -systemd -telemetry -xemacs -xfce X alsa bash-completion cuda dbus dist-kernel elogind hardened nvenc opengl pulseaudio vdpau vim-syntax vulkan wayland zsh-completion policykit -branding"

# OBS may need these
# USE+="screencast gstreamer gles2"
# TODO: remove a lot of these and set on individuial package basis instead

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8

GENTOO_MIRRORS="rsync://rsync.mirrorservice.org/distfiles.gentoo.org/ \
    https://mirror.bytemark.co.uk/gentoo/ \
    http://mirror.bytemark.co.uk/gentoo/ \
    https://www.mirrorservice.org/sites/distfiles.gentoo.org/"

ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

GRUB_PLATFORMS="efi-64"
