# monitor = name, resolution, position, scale
# position is from top left corner using an inverse Y cartesian system
monitor = DP-3, 1920x1080@240, 0x0, 1
monitor = DP-2, 1600x900@60, 1920x195, 1
exec-once=xrandr --output DP-3 --primary

# monitor = DP-2, disable
