# created by eselect-repo

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[phackerlay]
location = /var/db/repos/phackerlay
sync-type = git
sync-uri = https://gitlab.phys-el.ru/gentoo/phackerlay.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/microcai/gentoo-zh

[local-overlay]
location = /var/db/repos/local-overlay
