return {
  require "configs.conform",
  require "configs.dap",
  require "configs.dap-virtual-text",
  require "configs.dapui",
  require "configs.illuminate",
  require "configs.kitty-scrollback",
  require "configs.leap",
  require "configs.lint",
  require "configs.lspconfig",
  require "configs.mkdir",
  require "configs.mkdnflow",
  require "configs.nio",
  require "configs.overseer",
  require "configs.render-markdown",
  require "configs.tabtree",
  require "configs.telescope-dap",
  require "configs.toggleterm",
  require "configs.treesitter",
  -- require "configs.cinnamon",
  require "configs.sort",
  require "configs.undotree",
  require "configs.dial",
  require "configs.todo-comments",
}
